name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via SSH
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r * ec2-user@18.134.209.244:/home/ec2-user/app
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@18.134.209.244 << EOF
            cd /home/ec2-user/app
            npm install
            pm2 delete all || true
            pm2 start index.js
          EOF
